name: Update PR Status for Entregas

on:
  pull_request:
    types: [closed]
    branches:
      - 'entrega-*'

jobs:
  update-status-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository for entregas branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: entregas
          
      - name: Update status file
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"
          PR_DATE=$(date -u "+%Y-%m-%d %H:%M:%S UTC")
          TARGET_BRANCH="${{ github.event.pull_request.base.ref }}"
          
          # Obtener estadísticas de archivos modificados
          ADDITIONS=${{ github.event.pull_request.additions }}
          DELETIONS=${{ github.event.pull_request.deletions }}
          
          if ${{ github.event.pull_request.merged }}; then
            STATUS="MERGED"
          else
            STATUS="CLOSED"
          fi
          
          if [ ! -f entregas-status.txt ]; then
            echo "#PR|Descripción|Usuario|Fecha|Estado|Rama|Cambios" > entregas-status.txt
            echo "---|---|---|---|---|---|---" >> entregas-status.txt
          fi
          
          echo "#$PR_NUMBER|'$PR_TITLE'|$PR_AUTHOR|$PR_DATE|$STATUS|$TARGET_BRANCH|+$ADDITIONS-$DELETIONS" >> entregas-status.txt
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add entregas-status.txt
          git commit -m "Actualización del estado de la entrega del PR #${{ github.event.pull_request.number }}"
          git push
